tasks:
  - name: 💎 INSTALL 💎
    command: bash .install.sh
    openMode: split-right
  - name: 👷 HARDHAT 👷
    command: yarn
    
vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "JuanBlanco.solidity"
    - "NomicFoundation.hardhat-solidity"
